apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: my-image=<DOCKERHUB REPOSITORY NAME>
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    argocd-image-updater.argoproj.io/my-image.update-strategy: latest
spec:
  project: default
  source:
    repoURL: "https://github.com/DasukuXD/Terraform-test"
    targetRevision: HEAD
    path: "application/backend"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "application"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
