apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/DasukuXD/Terraform-test"
    targetRevision: HEAD
    path: "application/backend"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "application"
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
