name: "CI Pipeline"

on:
  pull_request:
    branches:
      - main
      - master
    types:
      - closed

permissions:
  contents: read

jobs:
  scan-source-code:
    name: Scan Code With Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy

      - name: Run Trivy Scan
        run: |
          trivy config .

  build-push-image:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: scan-terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Docker Build image
        run: docker build -t frontend-image ./application
